package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 05 11:47:09 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExcelViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ExcelViewImpl() {
    }
}
